-- =============================================================================
-- DEPRECADO — Archivo renombrado.
-- =============================================================================
-- La tabla `comprobantes_proveedor` fue renombrada a `fin_compras_comprobante`
-- en la migración `20260418290000_rename_7_tablas_prod_fin`.
--
-- Usar en su lugar: scripts/neon-fin-compras-comprobante.sql
--
-- Este archivo se mantiene únicamente como puntero histórico y no debe
-- ejecutarse. Cualquier ejecución es un no-op.
-- =============================================================================
